---
title: "Untitled"
author: "Arthur Augusto"
date: "2025-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Invertendo U

```{r}
set.seed(1712)

pUs <- function(x) 4*(x - 0.5)**3 + 0.5

qUs <-function(p) (p - 0.5)**(1/3) + 0.5

dUs <- function(x) 12*(x-0.5)**2

dUs(c(0,0.5,1))
pUs(c(0,0.5,1))
qUs(c(0,0.5,1))

qUs2 <- function(x) (as.complex(x - 0.5))**(1/3)
qUs2(c(0,0.5,1))


qUs <- function(p) ((sign(p - 0.5)*abs(p - 0.5))^(1/3) + 0.5)

qUs(c(0, 0.5, 1))
```

## teorema da inversa

Seja a v.a X pertencente aos reais, a variavel aleatoria $F_{x}^{-1}(U)$ tem a mesma distribuiçao de X, em que

$F_{x}^{-1}$: inversa generalizada da fda $F_x$ de X

U: V.A uniforme(0,1)

computacionalmente:

```{r}
set.seed(1712)

u <- runif(1E4)

x.us <- qUs(u)

hist(x.us, freq = F, breaks = 50, ylim = c(0,3))

t.test(x.us, mu = 0.5)

qUs(c(0.25,0.5,0.75))
```

ARRUMAR O CODIGO.

#### Explicaçao do erro, 26/04:

```{r}
qUs <- function(p) ((sign(p - 0.5)*abs(p - 0.5))^(1/3) + 0.5)

### deveria ser

qUs <- function(p) return(sign(p-0.5)*(abs(p/4 - 0.125))^(1/3) + 0.5)
```


